### ISSUE TITLE
Circuit.SetActiveBus(BusName) is not working

### ISSUE THREAD

**Issue by dougchristie-DukeEnergy** [dss-extensions/AltDSS-Go#3]
When working with an Circuit and solving a particular DSS diagram and I make a call to Circuit.SetActiveBus(BusName) the Active bus get overwritten with an empty string.  I made the following set of calls. 

        buses, err := Circuit.AllBusNames()
        println(buses)
        vmags, err := Circuit.AllBusVmagPu()
        prop, err := dssInstance.Circuit.ActiveCktElement.Properties.Get_Val()
        println(prop)
        println(vmags)
        busname1, err := Circuit.ActiveBus.Name()
        println(busname1)
        num, err := Circuit.SetActiveBus(BusName)
        busname2, err := Circuit.ActiveBus.Name()

From the screen shot below you can see the debugger values that of the resulting calls, and the buses that are available. The BusName value in the SetActiveBus call is "p4". 

![Screenshot 2023-12-21 at 4 39 17 PM (2)](https://github.com/dss-extensions/AltDSS-Go/assets/126599516/12efc6bf-a32b-412a-936c-b22111a6f08e)

**Comment by PMeira** [comment]
I think I see the issue (missing some `defer`), let me test and push a fix.

**Comment by dougchristie-DukeEnergy** [comment]
Awesome thank you.

**Comment by PMeira** [comment]
Done, should work now. It seems it was missing in 8 functions, `SetActiveBus` being one of them.

**Comment by dougchristie-DukeEnergy** [comment]
Yes the changes fixed the issue. Thanks for fixing that issue so quickly
